version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: nuredb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nestjs_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      JWT_SECRET: jwt_secret
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
